import { List, ListEnumerator } from './lists';
import {openJSON, saveJSON} from './files';
import {
    deepClone,
    debounce,
    throttle,
    generateRandomString,
    isInArray,
    formatNumberWithCommas,
    isNumber,
    isString,
    isBoolean,
    isObject,
    isFunction,
    isUndefined,
    isNull,
    isNullOrUndefined,
    isNullOrEmpty,
    findMaxValue,
    findMinValue,
    removeDuplicates,
    stringContainsSubstring,
    trimWhitespace,
    isValidEmail,
    getCurrentTimestamp,
    throwError,
    hasProperty,
    serializeToJSON,
    deserializeFromJSON,
    getKeys,
    getValues
} from './utils';

import {
    connectToMongoDB,
    queryDocuments,
    insertDocument,
    insertDocuments,
    updateDocument,
    updateDocuments,
    deleteDocument,
    deleteDocuments,
    countDocuments,
    createCollection,
    dropCollection,
    listCollections,
    listDatabases
} from './mdb';

import {
    connectToMySQLDatabase,
    executeQuery,
    insertData,
    updateData,
    deleteData,
    selectData,
    selectAllData
} from './msqldb';

export default { 
    List, ListEnumerator, 
    openJSON, saveJSON,
    deepClone,
    debounce,
    throttle,
    generateRandomString,
    isInArray,
    formatNumberWithCommas,
    isNumber,
    isString,
    isBoolean,
    isObject,
    isFunction,
    isUndefined,
    isNull,
    isNullOrUndefined,
    isNullOrEmpty,
    findMaxValue,
    findMinValue,
    removeDuplicates,
    stringContainsSubstring,
    trimWhitespace,
    isValidEmail,
    getCurrentTimestamp,
    throwError,
    hasProperty,
    serializeToJSON,
    deserializeFromJSON,
    getKeys,
    getValues,
    connectToMongoDB,
    queryDocuments,
    insertDocument,
    insertDocuments,
    updateDocument,
    updateDocuments,
    deleteDocument,
    deleteDocuments,
    countDocuments,
    createCollection,
    dropCollection,
    listCollections,
    listDatabases,
    connectToMySQLDatabase,
    executeQuery,
    insertData,
    updateData,
    deleteData,
    selectData,
    selectAllData
}